### ISSUE TITLE
Informations download fails without Ids

### ISSUE THREAD

**Issue by onufle** [lrpirlet/cal-noosfere#2]
Hi,

calibre version : 6.23
plugin version : noosfere DB (1, 2, 0) 

Since yesterday, it's no more possible to dowload epub informations from Noosfere. Error message copied below.

If Ids is setted (ex : nsfr_id:vl$4388) informations are downloaded. 

For a single book it's ok but it's painfull with many books.

`calibre, version 6.23.0
ERREUR : Aucune correspondance trouvée: <p>Impossible de trouver un livre correspondant à votre recherche. Essayer de faire une recherche <b>moins spécifique</b>. Par exemple, utiliser seulement le nom de famille de l'auteur et un mot distinctif du titre.<p> Pour voir le journal en entier, cliquer "Afficher les détails.

Running identify query with parameters: 
{'title': "Les Conquérants de l'univers", 'authors': ['F. Richard-Bessière'], 'identifiers': {}, 'timeout': 30} 
Using plugins: noosfere DB (1, 2, 0) 
The log from individual plugins is below 

****************************** noosfere DB (1, 2, 0) ****************************** 
Found 0 results 
Downloading from noosfere DB took 0.10830974578857422 
self.extended_publisher                                     :  True
self.dgb_lvl                                                :  7
self.set_priority_handling                                  :  oldest
self.with_isbn                                              :  False
self.balanced                                               :  False
self.must_be_editor                                         :  x
self.get_Prixobtenus                                        :  True
self.get_Citédanslespagesthématiquessuivantes               :  True
self.get_Citédansleslistesthématiquesdesoeuvressuivantes    :  True
self.get_CitédanslesConseilsdelecture                       :  True
self.get_Adaptations                                        :  True

Entering identify(self, log, result_queue, abort, title=None, authors=None,identifiers={}, timeout=30)
log          :  <calibre.utils.logging.ThreadSafeLog object at 0x7f54bfd5ec20>
result_queue :  <queue.Queue object at 0x7f54bfd5ebf0>
abort        :  <threading.Event object at 0x7f54bfd5e800>
title        :  Les Conquérants de l'univers
authors      :  ['F. Richard-Bessière'] <class 'list'>
identifiers  :  {} <class 'dict'>

ISBN value is :  None
nsfr_id value is :  None
"Clean" both the authors list and the title... 
 
In ret_clean_txt(self, log, text, swap = False )
 text         :  F. Richard-Bessière
 cleaned text :  F Richard Bessière
 return text from ret_clean_txt
 
In ret_clean_txt(self, log, text, swap = False )
 text         :  Les Conquérants de l'univers
 cleaned text :  Les Conquérants de l univers
 return text from ret_clean_txt
getting one or more book url
trying ISBN None
trying using authors and title

In ret_author_index(soup)
authors    :  ['f richard bessiere']
 In ret_soup(log, dbg_lvl, br, url, rkt=none, who='[__init__]')
 br  :  <Browser (not visiting a URL)>
 url :  https://www.noosfere.org/livres/noosearch.asp
 rkt :  {'Mots': 'f richard bessiere', 'auteurs': 'auteurs', 'ModeMoteur': 'MOTS-CLEFS', 'ModeRecherche': 'AND', 'recherche': '1', 'Envoyer': 'Envoyer'}
 Accessing url :  https://www.noosfere.org/livres/noosearch.asp
 search parameters :  {'Mots': 'f richard bessiere', 'auteurs': 'auteurs', 'ModeMoteur': 'MOTS-CLEFS', 'ModeRecherche': 'AND', 'recherche': '1', 'Envoyer': 'Envoyer'}
 formated parameters :  Mots=f+richard+bessiere&auteurs=auteurs&ModeMoteur=MOTS-CLEFS&ModeRecherche=AND&recherche=1&Envoyer=Envoyer
 In urlopen_with_retry(log, dbg_lvl, br, url, rkt, who)

 HTTP Error 500 is Internal Server Error, sorry

Plugin noosfere DB failed
Traceback (most recent call last):
  File "calibre_plugins.noosfere.__init__", line 69, in urlopen_with_retry
    sr = br.open(url,data=rkt,timeout=30)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/ebooks/metadata/sources/identify.py", line 47, in run
  File "calibre_plugins.noosfere.__init__", line 753, in identify
    author_index=self.ret_author_index(log, br, authors)
  File "calibre_plugins.noosfere.__init__", line 509, in ret_author_index
    soup = ret_soup(log, self.dbg_lvl, br, url, rkt=rkt )[0]
  File "calibre_plugins.noosfere.__init__", line 123, in ret_soup
    resp = urlopen_with_retry(log, dbg_lvl, br, url, rkt, who)
  File "calibre_plugins.noosfere.__init__", line 79, in urlopen_with_retry
    raise Exception('(ret_soup) Failed while acessing url : ',url)
Exception: ('(ret_soup) Failed while acessing url : ', 'https://www.noosfere.org/livres/noosearch.asp') 

******************************************************************************** 
The identify phase took 0.20 seconds 
The longest time (0.108310) was taken by: noosfere DB 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds 
`

**Comment by lrpirlet** [comment]
The log says: 
"HTTP Error 500 is Internal Server Error, sorry"
This seems to indicate problem on the server, not in the calibre side...

The log says: 
"Accessing url : https://www.noosfere.org/livres/noosearch.asp
search parameters : {'Mots': 'f richard bessiere', 'auteurs': 'auteurs', 'ModeMoteur': 'MOTS-CLEFS', 'ModeRecherche': 'AND', 'recherche': '1', 'Envoyer': 'Envoyer'}
formated parameters : Mots=f+richard+bessiere&auteurs=auteurs&ModeMoteur=MOTS-CLEFS&ModeRecherche=AND&recherche=1&Envoyer=Envoyer"

So, from a browser, opening [https://www.noosfere.org/livres/noosearch.asp](https://www.noosfere.org/livres/noosearch.asp) and entering "f richard bessiere" then ticking auteurs, then selecting MOTS-CLEFS', 'ModeRecherche' before sending the request  does return 
```
Microsoft OLE DB Driver for SQL Server erreur '80040e14'

La recherche en texte intégral n'est pas installée ou il est impossible de charger le composant de recherche en texte intégral.

/livres/noosearch.asp, ligne 521
```
Googeling that error '80040e14' confirms that the server is in error... The associated message seems to suggest that an exec is missing... One sure thing is that the search is broken on the server and there is absolutely nothing I can do...

I suggest you report the problem to Noosfere people. I am not in position to do it right now.

Since this is external to the program, I suggest you close it.

**Comment by onufle** [comment]
Thanks for this information, sure it's ok to close this one,
BR

**Comment by lrpirlet** [comment]
@onufle 

Answer from a responsible of noosfere:

Bonjour,
Merci de nous avoir signalé le problème. Nous avons effectivement migré notre serveur ce week-end, et toutes les fonctionnalités ne sont pas encore opérationnelles. Le retour à la normale devrait s'effectuer courant de semaine.
Cordialement
Bruno Para 
mardi, 25 juillet 2023, 10:14AM +02:00
